// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xzrlbuofvmdkjtfzcfsw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh6cmxidW9mdm1ka2p0ZnpjZnN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4NDEzMjEsImV4cCI6MjA2MzQxNzMyMX0.r0yvqTVLnhAlrqi5v-VYPNKswZQiXyvnQlhbs5d3vY4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);